### Requisição para a raiz
GET http://localhost:5244

### Listar Produto
GET http://localhost:5244/api/produto/listar

### Cadastrar Produto
POST http://localhost:5244/api/produto/cadastrar
Content-Type: application/json

{
    "nome" : "Mouse",
     "quantidade" : 123,
     "preco" : 85.5
}