### Requisição para a raiz
GET http://localhost:5244

### Listar Produto
GET http://localhost:5244/api/produto/listar

### Cadastrar Produto
POST http://localhost:5244/api/produto/cadastrar
Content-Type: application/json

{
    "nome" : "Teclado",
    "descricao" : "Eletrônico",
    "quantidade" : 123,
    "preco" : 3500
}

### Buscar produto por id
GET http://localhost:5244/api/produto/buscar/112aab04-16ab-48df-8ec4-1ad4f55710ac

### Remover produto por id
DELETE  http://localhost:5244/api/produto/remover/

### Alterar produto por id
PATCH http://localhost:5244/api/produto/alterar/112aab04-16ab-48df-8ec4-1ad4f55710ac
Content-Type: application/json

{
    "nome" : "MacBook",
     "quantidade" : 123,
     "preco" : 3500
}